# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "torch==2.5.1",
#     "transformers==4.46.3",
#     "peft==0.13.2",
#     "accelerate==1.1.1",
# ]
# ///
"""
Export the SakThai tool-calling adapter for local use via Ollama.

Step 1 (this script): merge the LoRA adapter into the base weights and save a
standalone HF model dir, then write an Ollama `Modelfile` carrying SakThai's
system prompt. This is the part that needs Python/transformers.

Step 2 (printed instructions): convert the merged dir to GGUF with llama.cpp
and register it with Ollama. Those are CLI tools, not Python deps, so the
script tells you the exact commands rather than shelling out to toolchains it
can't guarantee are installed.

After that, the agent runs entirely locally:
    sakthai run --provider ollama --model sakthai "Remember I use uv, never pip"

(The OpenAI/Ollama provider already targets 127.0.0.1:11434 per repo convention.)

Run:
    uv run training/serving/export_ollama.py --out ./sakthai-merged

Knobs via env:
    BASE_MODEL    default Qwen/Qwen2.5-1.5B-Instruct
    ADAPTER_REPO  default Nanthasit/sakthai-toolcalling-1.5b-lora
"""
import argparse
import os
import sys
from pathlib import Path

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "hf-jobs"))
from build_toolcalling_dataset import SYSTEM_PROMPT  # noqa: E402

BASE_MODEL = os.environ.get("BASE_MODEL", "Qwen/Qwen2.5-1.5B-Instruct")
ADAPTER_REPO = os.environ.get("ADAPTER_REPO", "Nanthasit/sakthai-toolcalling-1.5b-lora")

MODELFILE = """\
# Generated by export_ollama.py — SakThai local tool-calling model.
# After GGUF conversion (see export_ollama.py output), build with:
#   ollama create sakthai -f Modelfile
FROM ./sakthai-merged.gguf

# Qwen2.5 carries its chat template + tool-call format in the GGUF metadata,
# so Ollama uses it automatically; we only pin SakThai's persona + sampling.
SYSTEM \"\"\"{system}\"\"\"

PARAMETER temperature 0.2
PARAMETER top_p 0.9
PARAMETER stop "<|im_end|>"
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="./sakthai-merged", help="output dir for merged model")
    args = ap.parse_args()
    out = Path(args.out)

    print(f"== Loading base {BASE_MODEL} + adapter {ADAPTER_REPO}")
    tokenizer = AutoTokenizer.from_pretrained(ADAPTER_REPO)
    base = AutoModelForCausalLM.from_pretrained(BASE_MODEL, torch_dtype=torch.float16)
    model = PeftModel.from_pretrained(base, ADAPTER_REPO)

    print("== Merging adapter into base weights")
    merged = model.merge_and_unload()

    print(f"== Saving merged model to {out}")
    out.mkdir(parents=True, exist_ok=True)
    merged.save_pretrained(out, safe_serialization=True)
    tokenizer.save_pretrained(out)

    modelfile_path = out / "Modelfile"
    modelfile_path.write_text(MODELFILE.format(system=SYSTEM_PROMPT))
    print(f"== Wrote {modelfile_path}")

    print(
        "\n== Next steps (CLI tools — run these yourself):\n"
        "  # 1. Convert the merged HF dir to GGUF with llama.cpp:\n"
        f"  python /path/to/llama.cpp/convert_hf_to_gguf.py {out} \\\n"
        f"      --outfile {out}/sakthai-merged.gguf --outtype q8_0\n"
        "  # 2. Register with Ollama:\n"
        f"  cd {out} && ollama create sakthai -f Modelfile\n"
        "  # 3. Run the agent on it:\n"
        '  sakthai run --provider ollama --model sakthai "Remember I use uv, never pip"\n'
    )


if __name__ == "__main__":
    main()
